import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./globals.css";
import MobileNavBar from "@/components/MobileNavBar";
import DesktopNavBar from "@/components/DesktopNavBar";

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${rubik.className} antialiased`}
      >
          <MobileNavBar />
          <DesktopNavBar />
          {children}
      </body>
    </html>
  );
}
